spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    hikari:
      maximum-pool-size: 5

    username: root
    password: 123456
    url: jdbc:mysql://10.243.147.87:3306/db


logging:
  file:
    name: analysis.log

